name: Rust

on:
  push:
    tags:
      - 'v*.*.*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libdbus
      run: sudo apt-get install libdbus-1-dev
    - name: Build
      run: cargo build --release
    - run: strip target/release/lutris-runner-dbus
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/lutris-runner-dbus
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
